/* ======================================================================
   Keychron B1 Pro - macOS Layer Definitions (ZMK)
   ====================================================================== */
export const TRANS = { trans: true };
export const K = (t, h, sh, n, icon) => ({ t, h, sh, n, icon });

export const NUM_ROW = [
  K("`", "", "~"),
  K("1", "", "!"),
  K("2", "", "@"),
  K("3", "", "#"),
  K("4", "", "$"),
  K("5", "", "%"),
  K("6", "", "^"),
  K("7", "", "&"),
  K("8", "", "*"),
  K("9", "", "("),
  K("0", "", ")"),
  K("-", "", "_"),
  K("=", "", "+"),
  K("Backspace"),
];

export const SHIFT_ROW_BASE = () => [
  K("Shift ⇧"),
  K("Z"),
  K("X"),
  K("C"),
  K("V"),
  K("B"),
  K("N"),
  K("M"),
  K(",", "", "<"),
  K(".", "", ">"),
  K("/", "", "?"),
  K("Shift ⇧"),
];

export function tabRow(navLabel) {
  return [
    K("Tab", "Hyper", "", "Hyper = Ctrl + Shift + Cmd + Option, all at once"),
    K("Q"),
    K("W"),
    K("E"),
    K("R"),
    K("T"),
    K("Y"),
    K("U"),
    K("I"),
    K("O"),
    K("P"),
    K("[", "", "{"),
    K("]", "", "}"),
    K("\\", navLabel),
  ];
}

export function homeRow(funcLabel, symLabel, gui, ctrlLabel = "Ctrl", altLabel = "Alt") {
  return [
    K("Esc", funcLabel),
    K("A", ctrlLabel),
    K("S", gui),
    K("D", altLabel),
    K("F", "Shift ⇧"),
    K("G", symLabel),
    K("H", symLabel),
    K("J", "Shift ⇧"),
    K("K", altLabel),
    K("L", gui),
    K(";", ctrlLabel, ":"),
    K("'", "", '"'),
    K("Enter"),
  ];
}

export function bottomRowMac(navLabel, funcLabel) {
  return [
    K("∧"),
    K("⌥"),
    K("⌘"),
    K("Space", navLabel),
    K("⌘"),
    K("Fn", funcLabel, "", "Tap = one-shot Macro selector"),
    K("←"),
    [K("↑"), K("↓")],
    K("→"),
  ];
}

export const INERT13 = Array(13).fill(null);
export function inertRow5() {
  return [null, null, null, null, null, null, null, [null, null], null];
}

export function inertLayerRows() {
  return [
    [K("⇒ Base"), ...INERT13],
    Array(14).fill(null),
    Array(14).fill(null),
    Array(13).fill(null),
    Array(12).fill(null),
    inertRow5(),
  ];
}

export const B1PRO_MAC_LAYERS = {
  m_base: {
    platform: "mac",
    num: 0,
    name: "Base",
    rows: [
      [
        K("Esc", "Caps Lock"),
        K("Brightness −", "", "F1", "", "brightness-down"),
        K("Brightness +", "", "F2", "", "brightness-up"),
        K("⧉", "", "F3", "Mission Control"),
        K("Launchpad", "", "F4", "", "launchpad"),
        K("Spotlight Search", "", "F5", "", "search"),
        K("Lock Screen", "", "F6", "", "lock"),
        K("⏮", "", "F7", "Previous Track"),
        K("⏯", "", "F8", "Play/Pause"),
        K("⏭", "", "F9", "Next Track"),
        K("Mute", "", "F10", "", "mute"),
        K("Volume −", "", "F11", "", "volume-down"),
        K("Volume +", "", "F12", "", "volume-up"),
        K("Del"),
      ],
      NUM_ROW,
      tabRow("→ Navigation"),
      homeRow("→ Function", "→ Symbols", "⌘", "∧", "⌥"),
      SHIFT_ROW_BASE(),
      bottomRowMac("→ Navigation", "→ Function"),
    ],
  },

  m_func: {
    platform: "mac",
    num: 1,
    name: "Function",
    rows: [
      [
        K("⇒ Base"),
        K("F1"),
        K("F2"),
        K("F3"),
        K("F4"),
        K("F5"),
        K("F6"),
        K("F7"),
        K("F8"),
        K("F9"),
        K("F10"),
        K("F11"),
        K("F12"),
        K("Del"),
      ],
      [
        TRANS,
        K("BT 1", "", "", "Double-tap: pair BT 1"),
        K("BT 2", "", "", "Double-tap: pair BT 2"),
        K("BT 3", "", "", "Double-tap: pair BT 3"),
        K("2.4G", "", "", "Switch to 2.4GHz dongle"),
        TRANS,
        TRANS,
        K("×", "", "", "Numpad multiply"),
        K("÷", "", "", "Numpad divide"),
        K("+", "", "", "Numpad plus"),
        K("−", "", "", "Numpad minus"),
        K("Boot", "", "", "Long-press 3s: enter bootloader"),
        K("Search"),
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K("2.4G"),
        TRANS,
        K("Del"),
        K("7"),
        K("8"),
        K("9"),
        K("Backspace"),
        TRANS,
        TRANS,
        null,
      ],
      [
        null,
        K("∧"),
        K("⌘"),
        K("⌥"),
        K("⇧"),
        TRANS,
        K("Tab"),
        K("4"),
        K("5"),
        K("6"),
        K("Enter"),
        TRANS,
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K(","),
        K("1"),
        K("2"),
        K("3"),
        K("."),
        K("⌃⌘Space", "", "", "Emoji & symbols picker"),
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        K("0"),
        K("∧"),
        TRANS,
        K("Home"),
        [K("PgUp"), K("PgDn")],
        K("End"),
      ],
    ],
  },

  m_sym1: {
    platform: "mac",
    num: 2,
    name: "Symbols",
    rows: [
      [
        K("⇒ Base"),
        K("F13"),
        K("F14"),
        K("F15"),
        K("F16"),
        K("F17"),
        K("F18"),
        K("F19"),
        K("F20"),
        K("F21"),
        K("F22"),
        K("F23"),
        K("F24"),
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K("⌘0"),
        K("⌘−"),
        K("⌘="),
        TRANS,
      ],
      [
        K("`"),
        K("!"),
        K("@"),
        K("#"),
        K("$"),
        K("%"),
        K("^"),
        K("&"),
        K("*"),
        K("-", "", "", "Double-tap: _"),
        K("=", "", "", "Double-tap: +"),
        TRANS,
        TRANS,
        TRANS,
      ],
      [
        K("~"),
        K("∧"),
        K("⌘"),
        K("⌥"),
        K("⇧"),
        null,
        null,
        K("(", "", "", "2×: )  3×: ()"),
        K("{", "", "", "2×: }  3×: {}"),
        K("[", "", "", "2×: ]  3×: []"),
        TRANS,
        TRANS,
        K("="),
      ],
      [
        TRANS,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        K("<"),
        K(">"),
        K("?"),
        K("⌃⌘Space", "", "", "Emoji & symbols picker"),
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K("←"),
        [K("↑"), K("↓")],
        K("→"),
      ],
    ],
  },

  m_nav1: {
    platform: "mac",
    num: 3,
    name: "Navigation",
    rows: [
      [
        K("⇒ Base"),
        K("F13"),
        K("F14"),
        K("F15"),
        K("F16"),
        K("F17"),
        K("F18"),
        K("F19"),
        K("F20"),
        K("F21"),
        K("F22"),
        K("F23"),
        K("F24"),
        TRANS,
      ],
      [
        null,
        null,
        null,
        K("#"),
        null,
        K("Wheel ↓"),
        null,
        null,
        K("Space"),
        null,
        K("Mouse Btn 1"),
        K("Mouse ↑"),
        K("Mouse Btn 2"),
        null,
      ],
      [
        null,
        K("⌘Q"),
        K("⌘W"),
        K("Wheel ←"),
        K("Wheel ↑"),
        K("Wheel →"),
        K("⌘Y"),
        K("Del"),
        K("↑"),
        K("Backspace"),
        K("Mouse ←"),
        K("Mouse ↓"),
        K("Mouse →"),
        null,
      ],
      [
        null,
        K("∧"),
        K("⌘"),
        K("⌥"),
        K("⇧"),
        null,
        K("Home"),
        K("←"),
        K("↓"),
        K("→"),
        K("End"),
        null,
        null,
      ],
      [
        null,
        K("⌘Z"),
        K("⌘X"),
        K("⌘C", "", "", "2×: ⌘⇧C  3×: ⌃⇧C"),
        K("⌘V", "", "", "2×: ⌃V  3×: ⌃⇧V"),
        K("⌘B"),
        K("PgUp"),
        K("PgDn"),
        K("⌃⇧Tab"),
        K("⌃Tab"),
        K("⌘⇧/"),
        null,
      ],
      [
        K("Speed 1"),
        K("Speed 2"),
        K("Speed 3"),
        null,
        null,
        null,
        K("←"),
        [K("↑"), K("↓")],
        K("→"),
      ],
    ],
  },

  m_uat: { platform: "mac", num: 4, name: "Reserved", rows: inertLayerRows() },

  m_mcro: {
    platform: "mac",
    num: 5,
    name: "Macro Selector",
    rows: [
      [K("⇒ Base"), ...INERT13],
      [
        null,
        K("⇒ Function"),
        K("⇒ Symbols"),
        K("⇒ Navigation"),
        K("⇒ Reserved"),
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      Array(14).fill(null),
      Array(13).fill(null),
      Array(12).fill(null),
      inertRow5(),
    ],
  },
};
