/* ======================================================================
   Keychron B1 Pro - Windows Layer Definitions (ZMK)
   ====================================================================== */
import {
  TRANS,
  K,
  NUM_ROW,
  SHIFT_ROW_BASE,
  tabRow,
  homeRow,
  bottomRowWin,
  INERT13,
  inertRow5,
  inertLayerRows,
} from "./b1pro_mac_layers.js";

export const B1PRO_WIN_LAYERS = {
  w_base: {
    platform: "win",
    num: 6,
    name: "Base",
    rows: [
      [
        K("Esc", "Caps Lock"),
        K("F1"),
        K("F2"),
        K("F3"),
        K("F4"),
        K("F5"),
        K("F6"),
        K("F7"),
        K("F8"),
        K("F9"),
        K("F10"),
        K("F11"),
        K("F12"),
        K("Del"),
      ],
      NUM_ROW,
      tabRow("→ Navigation"),
      homeRow("→ Function", "→ Symbols", "Win"),
      SHIFT_ROW_BASE(),
      bottomRowWin("→ Navigation", "→ Function"),
    ],
  },

  w_func: {
    platform: "win",
    num: 7,
    name: "Function",
    rows: [
      [
        K("⇒ Base"),
        K("Brightness −", "", "F1"),
        K("Brightness +", "", "F2"),
        K("Win+Tab", "", "F3", "Task switcher"),
        K("Win+E", "", "F4", "File Explorer"),
        K("Search", "", "F5"),
        K("Win+L", "", "F6", "Lock PC"),
        K("Previous Track", "", "F7"),
        K("Play/Pause", "", "F8"),
        K("Next Track", "", "F9"),
        K("Mute", "", "F10"),
        K("Volume −", "", "F11"),
        K("Volume +", "", "F12"),
        K("Del"),
      ],
      [
        TRANS,
        K("BT 1", "", "", "Double-tap: pair BT 1"),
        K("BT 2", "", "", "Double-tap: pair BT 2"),
        K("BT 3", "", "", "Double-tap: pair BT 3"),
        K("2.4G", "", "", "Switch to 2.4GHz dongle"),
        TRANS,
        TRANS,
        K("×"),
        K("÷"),
        K("+"),
        K("−"),
        K("Boot", "", "", "Long-press 3s: enter bootloader"),
        K("Search"),
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K("Del"),
        K("7"),
        K("8"),
        K("9"),
        K("Backspace"),
        TRANS,
        TRANS,
        null,
      ],
      [
        null,
        K("Ctrl"),
        K("Win"),
        K("Alt"),
        K("Shift ⇧"),
        TRANS,
        K("Tab"),
        K("4"),
        K("5"),
        K("6"),
        K("Enter"),
        TRANS,
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K(","),
        K("1"),
        K("2"),
        K("3"),
        K("."),
        K("Win+.", "", "", "Emoji panel"),
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        K("0"),
        TRANS,
        TRANS,
        K("Home"),
        [K("PgUp"), K("PgDn")],
        K("End"),
      ],
    ],
  },

  w_sym1: {
    platform: "win",
    num: 8,
    name: "Symbols",
    rows: [
      [
        K("⇒ Base"),
        K("F13"),
        K("F14"),
        K("F15"),
        K("F16"),
        K("F17"),
        K("F18"),
        K("F19"),
        K("F20"),
        K("F21"),
        K("F22"),
        K("F23"),
        K("F24"),
        TRANS,
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        K("Ctrl+0", "", "", "Reset zoom"),
        K("Ctrl+−", "", "", "Zoom out"),
        K("Ctrl+=", "", "", "Zoom in"),
        TRANS,
      ],
      [
        K("`"),
        K("!"),
        K("@"),
        K("#"),
        K("$"),
        K("%"),
        K("^"),
        K("&"),
        K("*"),
        K("-", "", "", "Double-tap: _"),
        K("=", "", "", "Double-tap: +"),
        TRANS,
        TRANS,
        TRANS,
      ],
      [
        K("~"),
        K("Ctrl"),
        K("Win"),
        K("Alt"),
        K("Shift ⇧"),
        null,
        null,
        K("(", "", "", "2×: )  3×: ()"),
        K("{", "", "", "2×: }  3×: {}"),
        K("[", "", "", "2×: ]  3×: []"),
        TRANS,
        TRANS,
        K("="),
      ],
      [
        TRANS,
        null,
        null,
        null,
        null,
        null,
        null,
        K("<", "", "", "2×: >  3×: <>"),
        TRANS,
        TRANS,
        TRANS,
        K("Win+.", "", "", "Emoji panel"),
      ],
      [
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        TRANS,
        [TRANS, TRANS],
        TRANS,
      ],
    ],
  },

  w_nav1: {
    platform: "win",
    num: 9,
    name: "Navigation",
    rows: [
      [
        K("⇒ Base"),
        K("F13"),
        K("F14"),
        K("F15"),
        K("F16"),
        K("F17"),
        K("F18"),
        K("F19"),
        K("F20"),
        K("F21"),
        K("F22"),
        K("F23"),
        K("F24"),
        TRANS,
      ],
      [
        null,
        null,
        null,
        K("#"),
        null,
        K("Wheel ↓"),
        null,
        null,
        K("Space"),
        null,
        K("Mouse Btn 1"),
        K("Mouse ↑"),
        K("Mouse Btn 2"),
        null,
      ],
      [
        null,
        K("Alt+F4", "", "", "Close window"),
        K("Ctrl+W", "", "", "Close tab"),
        K("Wheel ←"),
        K("Wheel ↑"),
        K("Wheel →"),
        K("Ctrl+Y", "", "", "Redo"),
        K("Del"),
        K("↑"),
        K("Backspace"),
        K("Mouse ←"),
        K("Mouse ↓"),
        K("Mouse →"),
        null,
      ],
      [
        null,
        K("Ctrl"),
        K("Win"),
        K("Alt"),
        K("Shift ⇧"),
        null,
        K("Home"),
        K("←"),
        K("↓"),
        K("→"),
        K("End"),
        null,
        null,
      ],
      [
        null,
        K("Ctrl+Z"),
        K("Ctrl+X"),
        K("Ctrl+C"),
        K("Ctrl+V"),
        K("Ctrl+B"),
        K("PgUp"),
        K("PgDn"),
        K("Ctrl+Shift+Tab"),
        K("Ctrl+Tab"),
        K("Ctrl+Shift+/"),
        null,
      ],
      [
        K("Speed 1"),
        K("Speed 2"),
        K("Speed 3"),
        null,
        null,
        null,
        K("←"),
        [K("↑"), K("↓")],
        K("→"),
      ],
    ],
  },

  w_uat: { platform: "win", num: 10, name: "Reserved", rows: inertLayerRows() },

  w_mcro: {
    platform: "win",
    num: 11,
    name: "Macro Selector",
    rows: [
      [K("⇒ Base"), ...INERT13],
      [
        null,
        K("⇒ Function"),
        K("⇒ Symbols"),
        K("⇒ Navigation"),
        K("⇒ Reserved"),
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      Array(14).fill(null),
      Array(13).fill(null),
      Array(12).fill(null),
      inertRow5(),
    ],
  },
};
